runtime: php
env: flex

runtime_config:
    document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
    - .env
    - .env.example


handlers:
  - url: /(.*\.(gif|png|jpg|css|js))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js)$
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto


automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: production
    APP_KEY: base64:bpSgFkGEzI20NLp4mINRCzL8kgW6HLRGV1ZshzbCy9U=
    APP_NAME: "autobrokers"
    LOG_LEVEL: debug
    
SESSION_DRIVER: cookie

QUEUE_CONNECTION: sync

MAIL_MAILER: smtp
    MAIL_HOST: ""
    MAIL_PORT: 465
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: ssl
    MAIL_FROM_ADDRESS:
    MAIL_FROM_NAME: "Autobrokers"
PUSHER_APP_ID:
    PUSHER_APP_KEY:
    PUSHER_APP_SECRET:
    PUSHER_APP_CLUSTER: mt1
//the tmp folder is used for caching on GCP as opposed to the default storage folder
    APP_SERVICES_CACHE: /tmp/services.php
    APP_PACKAGES_CACHE: /tmp/packages.php
    APP_CONFIG_CACHE: /tmp/config.php
    APP_ROUTES_CACHE: /tmp/routes.php